# Aula 4

## Correspondencia de formas

In [1]:
import cv2
from matplotlib import pyplot as plt
import numpy as np

In [2]:
image = cv2.imread("imagens/shapes.jpg")
image_target = cv2.imread("imagens/star.jpg")

cv2.imshow("Fruits", image)
cv2.waitKey()

cv2.imshow("Target", image_target)
cv2.waitKey()
cv2.destroyAllWindows()

In [3]:
image_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
_, image_binary = cv2.threshold(image_gray, 230, 255,cv2.THRESH_BINARY_INV)
image_gray_target = cv2.cvtColor(image_target, cv2.COLOR_BGR2GRAY)
_, image_target_binary = cv2.threshold(image_gray_target, 230, 255,cv2.THRESH_BINARY_INV)

cv2.imshow("Fruits Binary", image_binary)
cv2.waitKey()

cv2.imshow("Target Binary", image_target_binary)
cv2.waitKey()

cv2.destroyAllWindows()

In [4]:
image_target_contour = image_target.copy()
_, contour_target, hierarchy = cv2.findContours(image_target_binary,cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
cv2.drawContours(image_target_contour, contour_target, 0, (0, 255, 0), 2)

cv2.imshow("Target Contour", image_target_contour)
cv2.waitKey()
cv2.destroyAllWindows()

In [5]:
# Match Shapes
# 3.4.1 com os algoritmos sem a remoção da lib
image_detected = image.copy()
cv2.imshow("Detected Binary", image_binary)

cv2.waitKey()
cv2.destroyAllWindows()

_, contours, hierarchy = cv2.findContours(image_binary, cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)

for contour in contours:
    #Quanto menor o valor mais similaridade existe
    match_perc = cv2.matchShapes(contour_target[0], contour, 1, 0)
    print(match_perc)
    cv2.drawContours(image_detected, [contour], 0, (0, 0, 255), 2)
    cv2.imshow("Detected", image_detected)
    cv2.waitKey()
    cv2.destroyAllWindows()
    if match_perc < 0.05:
        match_contour = contour
        cv2.drawContours(image_detected, [match_contour], 0, (0, 255, 0), 2)  

0.21697076862173215
0.10479351156122929
0.05397178326730856
0.24908817898612212
0.027009941605979915
0.23740218637769916


# Identificação de Retas

In [7]:
image = cv2.imread("imagens/campo.png")

cv2.imshow("Campo Futebol", image)
cv2.waitKey()
cv2.destroyAllWindows()

image_gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
image_edges = cv2.Canny(image_gray, 100, 250, apertureSize = 3)
image_detecada = image.copy()
lines = cv2.HoughLines(image_edges, 1, np.pi/180, 100)

In [9]:
for line in lines:
    print(line)
    for rho, theta in line:
        a = np.cos(theta)
        b = np.sin(theta)
        x0 = a*rho
        y0 = b*rho
        x1 = int(x0 + 1000*(-b))
        y1 = int(y0 + 1000*(a))
        x2 = int(x0 - 1000*(-b))
        y2 = int(y0 - 1000*(a))
        cv2.line(image_detecada,(x1,y1),(x2,y2),(0,0,255),2)
        
cv2.imshow("Campo Futebol Lines", image_detecada)
cv2.waitKey()
cv2.destroyAllWindows()

[[-263.           3.0892327]]
[[-260.           3.0892327]]
[[-15.          3.0892327]]
[[-18.          3.0892327]]
[[-265.          3.106686]]
[[-20.         3.106686]]
[[211.          1.5184364]]
[[28.         1.5184364]]
[[395.          1.5184364]]
[[398.          1.5184364]]
[[215.          1.5184364]]
[[30.         1.5184364]]


In [10]:
for line in lines:
    print(line)
    for rho, theta in line:
        a = np.cos(theta)
        b = np.sin(theta)
        x0 = a*rho
        y0 = b*rho
        x1 = int(x0 + 1000*(-b))
        y1 = int(y0 + 1000*(a))
        x2 = int(x0 - 1000*(-b))
        y2 = int(y0 - 1000*(a))
        cv2.line(image_detecada,(x1,y1),(x2,y2),(0,0,255),2)
        
cv2.imshow("Campo Futebol Lines", image_detecada)
cv2.waitKey()
cv2.destroyAllWindows()

[[-263.           3.0892327]]
[[-260.           3.0892327]]
[[-15.          3.0892327]]
[[-18.          3.0892327]]
[[-265.          3.106686]]
[[-20.         3.106686]]
[[211.          1.5184364]]
[[28.         1.5184364]]
[[395.          1.5184364]]
[[398.          1.5184364]]
[[215.          1.5184364]]
[[30.         1.5184364]]


# Correspondencia de Modelos

In [24]:
image = cv2.imread("imagens/mario.jpg")

cv2.imshow("Mario", image)
cv2.waitKey()

image_template = cv2.imread("imagens/coin_mario.jpg",cv2.IMREAD_GRAYSCALE)

cv2.imshow("Moeda Template", image_template)
cv2.waitKey()
cv2.destroyAllWindows()

image_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
image_matched = image.copy()
matched_template = cv2.matchTemplate(image_gray, image_template,cv2.TM_CCOEFF_NORMED)
w, h = image_template.shape[::-1]

In [25]:
threshold = 0.9
loc = np.where(matched_template >= threshold)
#Índice é a informação da coordenada
for pt in zip(*loc[::-1]):
    cv2.rectangle(image_matched, pt, (pt[0] + w, pt[1] + h), (0,255,0), 1)
    
    
cv2.imshow("Moeda Matched", image_matched)
cv2.waitKey()
cv2.destroyAllWindows()

In [21]:
image = cv2.imread("imagens/wally.jpg")

cv2.imshow("Wally", image)
cv2.waitKey()

image_template = cv2.imread("imagens/wally_face.jpg",cv2.IMREAD_GRAYSCALE)

cv2.imshow("Wally Template", image_template)
cv2.waitKey()
cv2.destroyAllWindows()

image_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
image_matched = image.copy()

In [22]:
matched_template = cv2.matchTemplate(image_gray, image_template, cv2.TM_CCOEFF_NORMED)

w, h = image_template.shape[::-1]

min_val, max_val, min_loc, max_loc = cv2.minMaxLoc(matched_template)
top_left = max_loc
bottom_right = (top_left[0] + w, top_left[1] + h)

cv2.rectangle(image_matched, top_left, bottom_right, (0,255,0), 2)
cv2.imshow("Moeda Matched", image_matched)
cv2.waitKey()
cv2.destroyAllWindows()

# Desafio 1
Em uma imagem de baralho completo, localize um 7 de Copas e o destaque com um retângulo, indicando com um texto acima a identificação da carta (“7 de Copas”).  
As imagens se encontram no repositório do GitHub.

In [40]:
image_baralho = cv2.imread("imagens/playing-cards.jpg")

cv2.imshow("Baralho", image_baralho)
cv2.waitKey()

image_7_espada = cv2.imread("imagens/playing-cards-7-copas.jpg")

cv2.imshow("7 de Espadas", image_7_espada)
cv2.waitKey()
cv2.destroyAllWindows()

In [41]:
image_baralho_gray = cv2.cvtColor(image_baralho, cv2.COLOR_BGR2GRAY)
image_7_espada_gray = cv2.cvtColor(image_7_espada, cv2.COLOR_BGR2GRAY)

In [42]:
matched_template = cv2.matchTemplate(image_baralho_gray, image_7_espada_gray, cv2.TM_CCOEFF_NORMED)

In [43]:
# Max e Min da maior semelhança
min_val, max_val, min_loc, max_loc = cv2.minMaxLoc(matched_template)
w, h = image_7_espada_gray.shape[::-1]

In [45]:
# Maior coordenada do match
top_left = max_loc
bottom_right = (top_left[0] + w, top_left[1] + h)

In [46]:
cv2.rectangle(image_baralho, top_left, bottom_right, (0, 255, 255), 2)

cv2.imshow("Encontrado", image_baralho)
cv2.waitKey()

cv2.destroyAllWindows()

# SIFT - Scale Invariance Feature Transform

In [52]:
# Instalar versao 3.4.1

image = cv2.imread("imagens/cristo.jpg")
cv2.imshow("Cristo Redentor", image)
cv2.waitKey()
cv2.destroyAllWindows()

image_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
sift_detector = cv2.xfeatures2d.SIFT_create()
(kps, descs) = sift_detector.detectAndCompute(image_gray, None)

print("Pontos detectados " + str(len(kps)))

image_detected = image.copy()

image_detected = cv2.drawKeypoints(image_detected, kps, image_detected,
flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)

cv2.imshow("Cristo Redentor Discriminant", image_detected)
cv2.waitKey()
cv2.destroyAllWindows()

AttributeError: module 'cv2.cv2' has no attribute 'SIFT'

# SURF - Speed Up Robust Features

In [53]:
image_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

surf_detector = cv2.xfeatures2d.SURF_create()
# Quando diminui o Threshold, aumenta a quantidade de pontos de interesse
surf_detector.setHessianThreshold(5000)
(kps, descs) = surf_detector.detectAndCompute(image_gray, None)

print("Pontos detectados " + str(len(kps)))

image_detected = image.copy()

image_detected = cv2.drawKeypoints(image_detected, kps, image_detected,
flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)

cv2.imshow("Cristo Redentor Discriminant", image_detected)
cv2.waitKey()
cv2.destroyAllWindows()

AttributeError: module 'cv2.cv2' has no attribute 'xfeatures2d'

# FAST - Feature from Accelerated Test

In [59]:
image_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

fast_detector = cv2.FastFeatureDetector_create()
kps = fast_detector.detect(image_gray, None)

print("Pontos detectados " + str(len(kps)))

image_detected = image.copy()
image_detected = cv2.drawKeypoints(image_detected, kps, image_detected,
flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)

cv2.imshow("Cristo Redentor Discriminant", image_detected)
cv2.waitKey()
cv2.destroyAllWindows()

Pontos detectados 1590


# BRIEF - Binary Robust Independent Elementary Features

In [60]:
image_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

fast_detector = cv2.FastFeatureDetector_create()
brief = cv2.xfeatures2d.BriefDescriptorExtractor_create()
kps = fast_detector.detect(image_gray, None)
kps, desc = brief.compute(image_gray, kps)

print("Pontos detectados " + str(len(kps)))

image_detected = image.copy()
image_detected = cv2.drawKeypoints(image_detected, kps, image_detected,
flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)

cv2.imshow("Cristo Redentor Discriminant", image_detected)
cv2.waitKey()
cv2.destroyAllWindows()

AttributeError: module 'cv2.cv2' has no attribute 'xfeatures2d'

# Correspondencia por força bruta

In [66]:
image_target = cv2.imread("imagens/cristo.jpg")
image_target_gray = cv2.cvtColor(image_target, cv2.COLOR_BGR2GRAY)

image_search = cv2.imread("imagens/cristo-redentor.jpg")
image_search_gray = cv2.cvtColor(image_search, cv2.COLOR_BGR2GRAY)

orb_detector = cv2.ORB_create(5000)
kps = orb_detector.detect(image_target_gray, None)
kps_target, desc_target = orb_detector.compute(image_target_gray, kps)
kps = orb_detector.detect(image_search_gray, None)
kps_search, desc_search = orb_detector.compute(image_search_gray, kps)

In [67]:
FLANN_INDEX_LSH = 6

index_params= dict(algorithm = FLANN_INDEX_LSH, table_number = 6, key_size = 12, multi_probe_level = 1)

search_params = dict(checks=50)

flann = cv2.FlannBasedMatcher(index_params, search_params)

matches = flann.knnMatch(desc_target, desc_search, k=2)

In [69]:
matchesMask = [[0,0] for i in range(len(matches))]
for i,(m,n) in enumerate(matches):
    if m.distance < 0.7*n.distance:
        matchesMask[i]=[1,0]

draw_params = dict(matchColor = (0,255,0), singlePointColor = (255,0,0),
matchesMask = matchesMask, flags = 0)
image_detected = cv2.drawMatchesKnn(image_target_gray, kps_target,
image_search_gray, kps_search, matches, None, **draw_params)
cv2.imshow("Cristo Redentor Discriminant", image_detected)
cv2.waitKey()
cv2.destroyAllWindows()

# Desafio 2
Utilize a imagem da embalagem do iogurte, conforme a baixo, como alvo para obter suas características. Posteriormente, faça o mesmo buscando tais características em um vídeo promocional, frame a frame, para identificar o quanto da embalagem é exposto.  

Aplique o algoritmo de extração de características de ORB. Para a correspondência de informações entre a embalagem e o vídeo, utilize o método de FLANN. Após testes, estabeleça um limiar de pontos de correspondência e, por meio deste valor, informe se a embalagem é detectada ou não com um texto no próprio vídeo.

In [2]:
image_target = cv2.imread("imagens/cristo.jpg")
image_target_gray = cv2.cvtColor(image_target, cv2.COLOR_BGR2GRAY)

image_search = cv2.imread("imagens/cristo-redentor.jpg")
image_search_gray = cv2.cvtColor(image_search, cv2.COLOR_BGR2GRAY)

orb_detector = cv2.ORB_create(5000)

kps = orb_detector.detect(image_target_gray, None)
kps_target, desc_target = orb_detector.compute(image_target_gray, kps)

kps = orb_detector.detect(image_search_gray, None)
kps_search, desc_search = orb_detector.compute(image_search_gray, kps)

In [5]:
FLANN_INDEX_LSH = 6
index_params= dict(algorithm = FLANN_INDEX_LSH, table_number = 6, key_size = 12, multi_probe_level = 1) 

search_params = dict(checks=50)

flann = cv2.FlannBasedMatcher(index_params, search_params)

matches = flann.knnMatch(desc_target, desc_search, k=2)

print(len(matches))

# Need to draw only good matches, so create a mask
matchesMask = [[0,0] for i in range(len(matches))]

# ratio test as per Lowe's paper
for i,(m,n) in enumerate(matches):
    if m.distance < 0.8*n.distance:
        matchesMask[i]=[1,0]
        
draw_params = dict(matchColor = (0,255,0), singlePointColor = (255,0,0), matchesMask = matchesMask, flags = 0)
image_detected = cv2.drawMatchesKnn(image_target_gray, kps_target, image_search_gray, kps_search, matches, None, **draw_params)

cv2.imshow("Cristo Redentor Discriminant", image_detected)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

1665


-1